name: Build

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]

jobs:
  iOS:
    if: github.event_name == 'release'
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Import signing keys
      run: |
        security create-keychain -p password build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain

        base64 -D <<< "${{ secrets.CERT_APPLE_DISTRIBUTION }}" > Apple_Distribution_Z52EFCPL6D.p7b
        security import ./Apple_Distribution_Z52EFCPL6D.p7b -k ~/Library/Keychains/build.keychain -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_APPLE_DEVELOPMENT }}" > Apple_Development_N952V7G2F5.p7b
        security import ./Apple_Development_N952V7G2F5.p7b -k ~/Library/Keychains/build.keychain -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_APPLE_DISTRIBUTION_P12 }}" > Apple_Distribution_Z52EFCPL6D.p12
        security import ./Apple_Distribution_Z52EFCPL6D.p12 -k ~/Library/Keychains/build.keychain -P heslo -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_APPLE_DEVELOPMENT_P12 }}" > Apple_Development_N952V7G2F5.p12
        security import ./Apple_Development_N952V7G2F5.p12 -k ~/Library/Keychains/build.keychain -P heslo -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_DEVELOPER_ID_APPLICATION }}" > Developer_ID_Application_Z52EFCPL6D.p7b
        security import ./Developer_ID_Application_Z52EFCPL6D.p7b -k ~/Library/Keychains/build.keychain -P heslo -T /usr/bin/codesign

        # Unlock
        security unlock-keychain -p password ~/Library/Keychains/build.keychain
        security set-keychain-settings -lu
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password ~/Library/Keychains/build.keychain

    - name: Import provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp dist/ios/*.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
        target: ios
    - name: Patch Qt
      run: |
        pushd $Qt5_Dir
        patch -p1 < $GITHUB_WORKSPACE/dist/ios/qt-ios.patch
        popd
    - name: Build the iOS binary
      run: |
        export TAG_NAME=$(./dist/get-tag-name.sh)
        bash ./dist/ios/build.sh
    - name: Upload artifacts to GitHub
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v2
      with:
        name: Lith.ipa
        path: build_ios/Lith.ipa
    - name: Upload to GitHub
      if: github.event_name == 'release'
      run: |
        export TAG_NAME=$(./dist/get-tag-name.sh)
        ./dist/upload-github-release-asset.sh github_api_token="${{ secrets.GITHUB_TOKEN }}" tag="$TAG_NAME" filename="build_ios/Lith.ipa"
    - name: Upload to Testflight
      if: github.event_name == 'release'
      run: |
        export TAG_NAME=$(./dist/get-tag-name.sh)
        xcrun altool --validate-app --file build_ios/Lith.ipa --username "${{ secrets.APPLEID_NAME }}" --password "${{ secrets.APPLEID_PASSWORD }}"
        xcrun altool --upload-app --file build_ios/Lith.ipa --username "${{ secrets.APPLEID_NAME }}" --password "${{ secrets.APPLEID_PASSWORD }}"

  Android-29:
    if: github.event_name == 'release'
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
        target: android
    - name: Get OpenSSL
      run: |
        git clone https://github.com/KDAB/android_openssl.git --depth=1
    - name: Build the Android binary
      run: |
        export ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk-bundle
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        bash ./dist/android/build.sh
    - name: Upload artifacts to GitHub
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v2
      with:
        name: android-build-debug.apk
        path: build_android/android-build//build/outputs/apk/debug/android-build-debug.apk
    - name: Upload to GitHub
      if: github.event_name == 'release'
      run: |
        TAG_NAME=$(./dist/get-tag-name.sh)
        ./dist/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} tag="$TAG_NAME" filename="build_android/android-build//build/outputs/apk/debug/android-build-debug.apk"

  Windows-MSVC:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build the application
      shell: bash
      run: |
        eval $(./dist/win/make-vs2019-env.bat)
        mkdir build
        cd build
        $Qt5_Dir/bin/qmake.exe ..
        nmake

  Linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Make
      run: |
        sudo apt update
        sudo apt install make
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build the application
      run: |
        mkdir build
        cd build
        $Qt5_Dir/bin/qmake ..
        make -j5

  macOS:
    runs-on: macOS-latest
    steps:
    - name: Import signing keys
      run: |
        security create-keychain -p password build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain

        base64 -D <<< "${{ secrets.CERT_APPLE_DISTRIBUTION }}" > Apple_Distribution_Z52EFCPL6D.p7b
        security import ./Apple_Distribution_Z52EFCPL6D.p7b -k ~/Library/Keychains/build.keychain -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_APPLE_DEVELOPMENT }}" > Apple_Development_N952V7G2F5.p7b
        security import ./Apple_Development_N952V7G2F5.p7b -k ~/Library/Keychains/build.keychain -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_APPLE_DISTRIBUTION_P12 }}" > Apple_Distribution_Z52EFCPL6D.p12
        security import ./Apple_Distribution_Z52EFCPL6D.p12 -k ~/Library/Keychains/build.keychain -P heslo -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_APPLE_DEVELOPMENT_P12 }}" > Apple_Development_N952V7G2F5.p12
        security import ./Apple_Development_N952V7G2F5.p12 -k ~/Library/Keychains/build.keychain -P heslo -T /usr/bin/codesign

        base64 -D <<< "${{ secrets.CERT_DEVELOPER_ID_APPLICATION }}" > Developer_ID_Application_Z52EFCPL6D.p7b
        security import ./Developer_ID_Application_Z52EFCPL6D.p7b -k ~/Library/Keychains/build.keychain -P heslo -T /usr/bin/codesign

        # Unlock
        security unlock-keychain -p password ~/Library/Keychains/build.keychain
        security set-keychain-settings -lu
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password ~/Library/Keychains/build.keychain
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build the application
      run: |
        ./dist/macos/build.sh
    - name: Generate .dmg
      run: |
        $Qt5_Dir/bin/macdeployqt build_macos/Lith.app -qmldir=. -dmg -appstore-compliant -codesign=Z52EFCPL6D
    - name: Upload artifacts to GitHub
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v2
      with:
        name: Lith.dmg
        path: build_macos/Lith.dmg
    - name: Upload to GitHub
      if: github.event_name == 'release'
      run: |
        TAG_NAME=$(./dist/get-tag-name.sh)
        ./dist/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} tag="$TAG_NAME" filename="build_macos/Lith.dmg"

